const questionsTypes = {
  CHECK_ANSWER: 'questions/CHECK_ANSWER',

  POST_TEST_START: 'questions/POST_TEST_START',
  POST_TEST_SUCCESS: 'questions/POST_TEST_SUCCESS',
  POST_TEST_FAILURE: 'questions/POST_TEST_FAILURE',

  SEND_RESULT_START: 'questions/SEND_RESULT_START',
  SEND_RESULT_SUCCESS: 'questions/SEND_RESULT_SUCCESS',
  SEND_RESULT_FAILURE: 'questions/SEND_RESULT_FAILURE',

  RESULTS_FINISHED_START: 'questions/RESULTS_FINISHED_START',
  RESULTS_FINISHED_SUCCESS: 'questions/RESULTS_FINISHED_SUCCESS',
  RESULTS_FINISHED_FAILURE: 'questions/RESULTS_FINISHED_FAILURE',

  RESULTS_START: 'questions/RESULTS_START',
  RESULTS_SUCCESS: 'questions/RESULTS_SUCCESS',
  RESULTS_FAILURE: 'questions/RESULTS_FAILURE',

  RESET_QUESTIONS: 'questions/RESET_QUESTIONS',
};

export default questionsTypes;
