export default {
  RESULTS_START: 'questions/RESULTS_START',
  RESULTS_SUCCESS: 'questions/RESULTS_SUCCESS',
  RESULTS_FAILURE: 'questions/RESULTS_FAILURE',

  POST_TEST_START: 'questions/POST_TEST_START',
  POST_TEST_SUCCESS: 'questions/POST_TEST_SUCCESS',
  POST_TEST_FAILURE: 'questions/POST_TEST_FAILURE',
};
